services:
  - type: web
    name: trading-app
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn main:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.7
      - key: TWELVE_DATA_API_KEY
        sync: false
      - key: POLYGON_API_KEY
        sync: false
      - key: STRIPE_PUBLISHABLE_KEY
        sync: false
      - key: STRIPE_SECRET_KEY
        sync: false
      - key: STRIPE_PREMIUM_PRICE_CENTS
        value: "999"
